# SPDX-FileCopyrightText: 2026 Watanabe Takanobu
# SPDX-License-Identifier: GPL-3.0-only
[package]
name = "oyatsu"
version = "0.3.0"
description = "Seasonal time system clock"
authors = ["Watanabe Takanobu <rreedd555@gmail.com>"]
categories = ["command-line-utilities"]
edition = "2024"
rust-version = "1.86"
readme = "README.md"
homepage = "https://github.com/tknv/oyatsu"
license = "GPL-3.0-only"
repository = "https://github.com/tknv/oyatsu"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }

[profile.release]
strip = true
lto = true
opt-level = "z"

# =========================================
# Debian パッケージ (.deb) 向けの設定
# =========================================
[package.metadata.deb]
assets = [
    # [コピー元ファイル, インストール先ディレクトリ, パーミッション]
    ["target/release/oyatsu", "usr/bin/", "755"],
    ["oyatsu.1", "usr/share/man/man1/", "644"],
    ["README.md", "usr/share/doc/oyatsu/README.md", "644"],
]

# =========================================
# RPM パッケージ (.rpm) 向けの設定
# =========================================
[package.metadata.generate-rpm]
assets = [
    { source = "target/release/oyatsu", dest = "/usr/bin/oyatsu", mode = "755" },
    { source = "oyatsu.1", dest = "/usr/share/man/man1/oyatsu.1", mode = "644" },
    { source = "README.md", dest = "/usr/share/doc/oyatsu/README.md", doc = true, mode = "644" },
]
